export const how_does_data = [
  {
    title: "Creating Markets",
    description:
      "We create engaging prediction markets using reliable weather APIs like OpenWeather and NOAA",
  },
  {
    title: "Setting Odds and Trading Shares",
    description:
      "Market odds are generated by the users' decisions.  Shares are created when opposing participants agree on the odds, with each pair fully collateralized in USDC.",
  },
  {
    title: "Resolving Markets and Payouts",
    description:
      "Markets are resolved using data from credible sources like NWS. Winning shares are paid $1.00 USDC each.",
  },
];

export const why_data = [
  {
    imageurl: "/about-us/infinite.svg",
    alt: "infinite",
    width: 80,
    height: 40,
    title: "Always On",
    description: [
      "Weather events occur year-round,",
      "offering continuous market opportunities.",
    ],
  },
  {
    imageurl: "/about-us/star.svg",
    alt: "star",
    width: 42,
    height: 40,
    title: "Limitless Options",
    description: ["Bet on global locations and", "diverse weather phenomena."],
  },
  {
    imageurl: "/footerpad/people-clicked.svg",
    alt: "community",
    width: 50,
    height: 40,
    title: "Community",
    description: [
      "Engage with weather enthusiasts",
      "on social media and our interactive forums.",
    ],
  },
  {
    imageurl: "/about-us/diamond.svg",
    alt: "diamond",
    width: 43.6,
    height: 40,
    title: "Value Beyond Prediction Markets",
    description: [
      "Prediction market data enhances weather",
      "modeling and reflects public sentiment on",
      "climate forecasts.",
    ],
  },
];

export const why_choose_data = [
  {
    title: ["Transparent", "and Reliable"],
    description_1: [
      "Markets are resolved",
      "using trusted data from",
      "sources like NOAA and",
      "OpenWeather.",
    ],
    description_2: [
      "Every market has a",
      "definitive timeframe and",
      "clear resolution criteria",
    ],
  },
  {
    title: ["Community", "Oriented"],
    description_1: ["Engage in discussions with", "weather enthusiasts."],
    description_2: ["Access live forecasts and", "interactive maps."],
  },
  {
    title: ["Accesible", "and Fair"],
    description_1: ["Trade with others, not", "not the house"],
    description_2: ["No penalties for winning", "too much."],
  },
];

export const gettingstarted_data = [
  {
    title: "Create an Account",
    description: [
      "Sign up with your email or crypto",
      "wallet to access the platform",
    ],
  },
  {
    title: "Fund Your Wallet",
    description: ["Deposit USDC to trade in", "weather markets"],
  },
  {
    title: "Explore Markets",
    description: ["Choose from a wide range", "of weather-related predictions"],
  },
  {
    title: "Buy Shares",
    description: ['Select "YES" or "NO" shares for', "your preferred outcome"],
  },
  {
    title: "Track and Trade",
    description: [
      "Monitor your markets and",
      "trade shares to lock in profits",
      "or minimize losses.",
    ],
  },
];

export const FAQ_data = [
  {
    question: "Why use USDC for trading?",
    answer:
      "USDC provides a stable and widely accepted currency for transparent and secure transactions.",
  },
  {
    question: "Can I sell early?",
    answer:
      "We do not currently have this function, but we are working on integrating it in the future.",
  },
  {
    question: "Does Better Weather have a token?",
    answer:
      "Better Weather is considering launching a token, but there is currently no token minted by us. All tokens with the name Better Weather are not affiliated with us.",
  },
  {
    question: "How do i contact support?",
    answer:
      "How do I contact support? = Email betterweatherbiz@gmail.com for inquiries.",
  },
];

export const Termsofuse_data = [
  {
    title: "1. Acceptance of Terms",
    content:
      'By accessing or using the Better Weather platform ("Platform"), you agree to comply with and be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Platform.',
  },
  {
    title: "2. Eligibility",
    content:
      "You must be at least 18 years old and legally capable of entering into binding contracts to use the Platform. By using the Platform, you represent and warrant that you meet these requirements.",
  },
  {
    title: "3. Account Registration",
    content:
      "To access certain features, you may need to create an account. You agree to provide accurate and complete information during registration and to keep this information up-to-date. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
  },
  {
    title: "4. Use of the Platform",
    content:
      "You agree to use the Platform in compliance with all applicable laws and regulations. You shall not:\n- Engage in any unlawful or fraudulent activities.\n- Interfere with or disrupt the operation of the Platform.\n- Attempt to gain unauthorized access to any part of the Platform or its related systems.",
  },
  {
    title: "5. Prediction Markets",
    content:
      "Better Weather offers prediction markets based on weather events. By participating, you acknowledge and agree that:\n- All trades are final and non-reversible.\n- Market outcomes are determined based on data from reputable sources.\n- Better Weather does not guarantee the accuracy or reliability of market information.",
  },
  {
    title: "6. Fees and Payments",
    content:
      "Participation in prediction markets may involve fees, which will be clearly disclosed. You agree to pay all applicable fees and authorize Better Weather to deduct such fees from your account.",
  },
  {
    title: "7. Intellectual Property",
    content:
      "All content on the Platform, including text, graphics, logos, and software, is the property of Better Weather or its licensors and is protected by intellectual property laws. You may not reproduce, distribute, or create derivative works from any content without prior written consent.",
  },
  {
    title: "8. Privacy",
    content:
      "Your use of the Platform is subject to our Privacy Policy, which outlines how we collect, use, and protect your personal information.",
  },
  {
    title: "9. Limitation of Liability",
    content:
      "To the fullest extent permitted by law, Better Weather shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Platform.",
  },
  {
    title: "10. Indemnification",
    content:
      "You agree to indemnify and hold harmless Better Weather and its affiliates from any claims, damages, losses, or liabilities arising from your use of the Platform or violation of these Terms.",
  },
  {
    title: "11. Termination",
    content:
      "Better Weather reserves the right to suspend or terminate your account and access to the Platform at its sole discretion, without notice, for conduct that it believes violates these Terms or is harmful to other users.",
  },
  {
    title: "12. Governing Law",
    content:
      "These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Better Weather operates, without regard to its conflict of law principles.",
  },
  {
    title: "13. Changes to Terms",
    content:
      "Better Weather may modify these Terms at any time. Any changes will be effective immediately upon posting on the Platform. Your continued use of the Platform constitutes acceptance of the revised Terms.",
  },
  {
    title: "14. Contact Information",
    content:
      "For any questions or concerns regarding these Terms, please contact us at betterweatherbiz@gmail.com.",
  },
];
